version: '2'
# Services
services:
  # PHP Service
  crm_php:
    container_name: crm_php
    image: crm:latest
    build:
      context: ..
      dockerfile: compose/php/Dockerfile
    volumes:
      - ../app:/var/www/app/:rw
    depends_on:
      - crm_mysql
  crm_composer:
    image: composer/composer:2.5.5

  # Nginx Service
  crm_nginx:
    container_name: crm_nginx
    image: nginx:1.23
    ports:
      - '80:80'
    restart: always
    links:
      - 'crm_php:php'
    volumes:
      - ../app:/var/www/app/:rw
      - ./nginx-conf:/etc/nginx/conf.d/:ro
    depends_on:
      - crm_php

  # MariaDB Service
  crm_mysql:
    container_name: crm_mysql
    image: mariadb:10.3
    ports:
      - '3306:3306'
    env_file:
      - ../app/.env
    volumes:
      - crm_mysql_data:/var/lib/mysql
  crm_pma:
    container_name: crm_pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: crm_mysql
    depends_on:
      - crm_mysql

# Volumes
volumes:
  crm_mysql_data:
