version: '2'
# Services
services:
  # PHP Service
  ontoloo_php:
    container_name: ontoloo_php
    build:
      dockerfile: php/Dockerfile
    volumes:
      - ../app:/var/www/ontoloo/:rw
    depends_on:
      - ontoloo_mysql

  # Nginx Service
  nginx:
    container_name: ontoloo_nginx
    image: nginx:1.23
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links:
      - 'ontoloo_php:php'
    volumes:
      - ../app:/var/www/ontoloo/:rw
      - ./nginx-conf:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs/:ro
    depends_on:
      - ontoloo_php

  # MariaDB Service
  ontoloo_mysql:
    container_name: ontoloo_mysql
    image: mariadb:10.3
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - ontoloo_mysql_data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    container_name: ontoloo_pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ontoloo_mysql
    depends_on:
      - ontoloo_mysql

# Volumes
volumes:
  ontoloo_mysql_data:
